
linters:
  enable:
    - bodyclose
    - depguard
    - dupl
    - errorlint
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gocognit
    - goconst
    - godox
    - goimports
    - gomnd
    - gosec
    - makezero
    - misspell
    - nilerr
    - prealloc
    - revive
    - tagliatelle
    - unconvert
    - unparam
    - wastedassign
  fast: false

linters-settings:
  dupl:
    threshold: 100

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - scopelint
  max-issues-per-linter: 0
