
linters:
  enable:
    - misspell
    - goimports
    - gosec
    - golint
    - goconst
    - unparam
    - gocognit
    - unconvert
    - scopelint
    - maligned
    - dupl
    - depguard
    - bodyclose
    - prealloc
    - godox
  fast: false

linters-settings:
  dupl:
    threshold: 100

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - scopelint
  max-issues-per-linter: 0
