
linters:
  enable:
    - bodyclose
    - depguard
    - dupl
    - ifshort
    - gocognit
    - goconst
    - godox
    - goimports
    - golint
    - gosec
    - maligned
    - misspell
    - prealloc
    - scopelint
    - unconvert
    - unparam
  fast: false

linters-settings:
  dupl:
    threshold: 100

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - scopelint
  max-issues-per-linter: 0
